// Maps Football-Data.org's team names to our seed names. Add a row whenever the
// remote feed uses a spelling that doesn't match what's in supabase/seed/matches.sql.
// Anything not in this map passes through unchanged, so the common case is no-op.
export const REMOTE_TO_LOCAL_TEAM: Record<string, string> = {
  USA: "United States",
  "United States of America": "United States",
  "Korea Republic": "South Korea",
  "Republic of Korea": "South Korea",
  "Côte d'Ivoire": "Ivory Coast",
  "Cote d'Ivoire": "Ivory Coast",
  "Czechia": "Czech Republic",
  "Türkiye": "Turkey",
  "Turkiye": "Turkey",
  "Cabo Verde": "Cape Verde",
  "Cape Verde Islands": "Cape Verde",
  "Bosnia-Herzegovina": "Bosnia and Herzegovina",
  "DR Congo": "DR Congo",
  "Congo DR": "DR Congo",
  "Democratic Republic of the Congo": "DR Congo",
  "Curacao": "Curaçao",

  // Liga MX clubs — football-data.org (FD) and ESPN naming conventions.
  "Club América": "América",
  "Club America": "América",
  "America": "América",
  "Atlas": "Atlas",
  "Atlético San Luis": "Atlético San Luis",
  "Atletico San Luis": "Atlético San Luis",
  "Cruz Azul": "Cruz Azul",
  "FC Juárez": "FC Juárez",
  "FC Juarez": "FC Juárez",
  "Juárez": "FC Juárez",
  "Juarez": "FC Juárez",
  "Guadalajara": "Guadalajara",
  "Chivas": "Guadalajara",
  "Club Deportivo Guadalajara": "Guadalajara",
  "León": "León",
  "Leon": "León",
  "Mazatlán": "Mazatlán",
  "Mazatlan": "Mazatlán",
  "Mazatlán FC": "Mazatlán",
  "Mazatlan FC": "Mazatlán",
  "Monterrey": "Monterrey",
  "CF Monterrey": "Monterrey",
  "Necaxa": "Necaxa",
  "Club Necaxa": "Necaxa",
  "Pachuca": "Pachuca",
  "CF Pachuca": "Pachuca",
  "Puebla": "Puebla",
  "Club Puebla": "Puebla",
  "Querétaro": "Querétaro",
  "Queretaro": "Querétaro",
  "Santos Laguna": "Santos Laguna",
  "Club Santos Laguna": "Santos Laguna",
  "Tijuana": "Tijuana",
  "Club Tijuana": "Tijuana",
  "Xolos": "Tijuana",
  "Toluca": "Toluca",
  "Deportivo Toluca": "Toluca",
  "UANL": "UANL",
  "Tigres UANL": "UANL",
  "Tigres": "UANL",
  "UNAM": "UNAM",
  "Pumas UNAM": "UNAM",
  "Pumas": "UNAM",

  // La Liga clubs — football-data.org (FD) and ESPN naming conventions.
  "Alavés": "Alavés",
  "Alaves": "Alavés",
  "Deportivo Alavés": "Alavés",
  "Athletic Club": "Athletic Club",
  "Athletic Bilbao": "Athletic Club",
  "Athletic de Bilbao": "Athletic Club",
  "Atlético Madrid": "Atlético Madrid",
  "Atletico Madrid": "Atlético Madrid",
  "Club Atlético de Madrid": "Atlético Madrid",
  "FC Barcelona": "Barcelona",
  "Barcelona": "Barcelona",
  "Real Betis": "Betis",
  "Betis": "Betis",
  "Real Betis Balompié": "Betis",
  "Celta Vigo": "Celta Vigo",
  "RC Celta de Vigo": "Celta Vigo",
  "Celta": "Celta Vigo",
  "Espanyol": "Espanyol",
  "RCD Espanyol": "Espanyol",
  "Getafe": "Getafe",
  "Getafe CF": "Getafe",
  "Girona": "Girona",
  "Girona FC": "Girona",
  "Las Palmas": "Las Palmas",
  "UD Las Palmas": "Las Palmas",
  "Leganés": "Leganés",
  "Leganes": "Leganés",
  "CD Leganés": "Leganés",
  "Mallorca": "Mallorca",
  "RCD Mallorca": "Mallorca",
  "Osasuna": "Osasuna",
  "CA Osasuna": "Osasuna",
  "Rayo Vallecano": "Rayo Vallecano",
  "Rayo": "Rayo Vallecano",
  "Real Madrid": "Real Madrid",
  "Real Madrid CF": "Real Madrid",
  "Real Sociedad": "Real Sociedad",
  "Sociedad": "Real Sociedad",
  "Sevilla": "Sevilla",
  "Sevilla FC": "Sevilla",
  "Valencia": "Valencia",
  "Valencia CF": "Valencia",
  "Valladolid": "Valladolid",
  "Real Valladolid": "Valladolid",
  "Villarreal": "Villarreal",
  "Villarreal CF": "Villarreal",
};

export function normalizeTeamName(remote: string | null | undefined): string {
  if (!remote) return "";
  const trimmed = remote.trim();
  return REMOTE_TO_LOCAL_TEAM[trimmed] ?? trimmed;
}
