-- Daily Quiz seed — ~30 World Cup trivia questions, one per UTC date starting
-- 2026-06-06. Idempotent on active_on (unique); re-running is a no-op.
-- Apply with: psql "$DATABASE_URL" -f supabase/seed/quiz.sql  (or supabase db reset locally).
--
-- The translations column carries positionally-aligned es/fr translations of
-- the prompt + options. English (the base prompt/options columns) is canonical;
-- correct_index grades every locale the same because option order is identical.
-- GENERATED from scripts/gen-quiz-translations.mjs — edit there, then re-run.

insert into public.quiz_questions (prompt, options, correct_index, active_on, translations) values
  ('How often is the men''s FIFA World Cup held?', array['Every 4 years','Every 2 years','Every 3 years','Every year'], 0, '2026-06-05', '{"es":{"prompt":"¿Cada cuánto se celebra la Copa Mundial masculina de la FIFA?","options":["Cada 4 años","Cada 2 años","Cada 3 años","Cada año"]},"fr":{"prompt":"À quelle fréquence a lieu la Coupe du monde masculine de la FIFA ?","options":["Tous les 4 ans","Tous les 2 ans","Tous les 3 ans","Tous les ans"]}}'::jsonb),
  ('Which country won the first FIFA World Cup, in 1930?', array['Uruguay','Brazil','Argentina','Italy'], 0, '2026-06-06', '{"es":{"prompt":"¿Qué país ganó la primera Copa Mundial de la FIFA, en 1930?","options":["Uruguay","Brasil","Argentina","Italia"]},"fr":{"prompt":"Quel pays a remporté la première Coupe du monde de la FIFA, en 1930 ?","options":["Uruguay","Brésil","Argentine","Italie"]}}'::jsonb),
  ('How many World Cups has Brazil won?', array['3','4','5','6'], 2, '2026-06-07', '{"es":{"prompt":"¿Cuántas Copas Mundiales ha ganado Brasil?","options":["3","4","5","6"]},"fr":{"prompt":"Combien de Coupes du monde le Brésil a-t-il remportées ?","options":["3","4","5","6"]}}'::jsonb),
  ('Which country hosted and won the 1998 World Cup?', array['France','Brazil','Italy','Spain'], 0, '2026-06-08', '{"es":{"prompt":"¿Qué país organizó y ganó la Copa Mundial de 1998?","options":["Francia","Brasil","Italia","España"]},"fr":{"prompt":"Quel pays a organisé et remporté la Coupe du monde 1998 ?","options":["France","Brésil","Italie","Espagne"]}}'::jsonb),
  ('Who won the 2022 World Cup in Qatar?', array['Argentina','France','Croatia','Brazil'], 0, '2026-06-09', '{"es":{"prompt":"¿Quién ganó la Copa Mundial de 2022 en Catar?","options":["Argentina","Francia","Croacia","Brasil"]},"fr":{"prompt":"Qui a remporté la Coupe du monde 2022 au Qatar ?","options":["Argentine","France","Croatie","Brésil"]}}'::jsonb),
  ('Who scored the "Hand of God" goal in 1986?', array['Diego Maradona','Pelé','Zico','Michel Platini'], 0, '2026-06-10', '{"es":{"prompt":"¿Quién marcó el gol de «la Mano de Dios» en 1986?","options":["Diego Maradona","Pelé","Zico","Michel Platini"]},"fr":{"prompt":"Qui a marqué le but de « la Main de Dieu » en 1986 ?","options":["Diego Maradona","Pelé","Zico","Michel Platini"]}}'::jsonb),
  ('Which nation has appeared in every World Cup?', array['Brazil','Germany','Italy','Argentina'], 0, '2026-06-11', '{"es":{"prompt":"¿Qué selección ha estado presente en todas las Copas Mundiales?","options":["Brasil","Alemania","Italia","Argentina"]},"fr":{"prompt":"Quelle nation a participé à toutes les Coupes du monde ?","options":["Brésil","Allemagne","Italie","Argentine"]}}'::jsonb),
  ('Who is the all-time top scorer in World Cup finals?', array['Miroslav Klose','Ronaldo','Gerd Müller','Pelé'], 0, '2026-06-12', '{"es":{"prompt":"¿Quién es el máximo goleador histórico en fases finales de la Copa Mundial?","options":["Miroslav Klose","Ronaldo","Gerd Müller","Pelé"]},"fr":{"prompt":"Qui est le meilleur buteur de l''histoire en phase finale de Coupe du monde ?","options":["Miroslav Klose","Ronaldo","Gerd Müller","Pelé"]}}'::jsonb),
  ('Where was the 1966 World Cup held?', array['England','West Germany','Mexico','Chile'], 0, '2026-06-13', '{"es":{"prompt":"¿Dónde se celebró la Copa Mundial de 1966?","options":["Inglaterra","Alemania Occidental","México","Chile"]},"fr":{"prompt":"Où s''est déroulée la Coupe du monde 1966 ?","options":["Angleterre","Allemagne de l''Ouest","Mexique","Chili"]}}'::jsonb),
  ('Which country won the 2010 World Cup?', array['Spain','Netherlands','Germany','Uruguay'], 0, '2026-06-14', '{"es":{"prompt":"¿Qué país ganó la Copa Mundial de 2010?","options":["España","Países Bajos","Alemania","Uruguay"]},"fr":{"prompt":"Quel pays a remporté la Coupe du monde 2010 ?","options":["Espagne","Pays-Bas","Allemagne","Uruguay"]}}'::jsonb),
  ('How many countries are hosting the 2026 World Cup?', array['1','2','3','4'], 2, '2026-06-15', '{"es":{"prompt":"¿Cuántos países organizan la Copa Mundial de 2026?","options":["1","2","3","4"]},"fr":{"prompt":"Combien de pays organisent la Coupe du monde 2026 ?","options":["1","2","3","4"]}}'::jsonb),
  ('How many teams play in the 2026 World Cup?', array['32','40','48','64'], 2, '2026-06-16', '{"es":{"prompt":"¿Cuántas selecciones juegan la Copa Mundial de 2026?","options":["32","40","48","64"]},"fr":{"prompt":"Combien d''équipes jouent la Coupe du monde 2026 ?","options":["32","40","48","64"]}}'::jsonb),
  ('Which country won the 2014 World Cup?', array['Germany','Argentina','Brazil','Netherlands'], 0, '2026-06-17', '{"es":{"prompt":"¿Qué país ganó la Copa Mundial de 2014?","options":["Alemania","Argentina","Brasil","Países Bajos"]},"fr":{"prompt":"Quel pays a remporté la Coupe du monde 2014 ?","options":["Allemagne","Argentine","Brésil","Pays-Bas"]}}'::jsonb),
  ('Who won the Golden Ball at the 2022 World Cup?', array['Lionel Messi','Kylian Mbappé','Luka Modrić','Neymar'], 0, '2026-06-18', '{"es":{"prompt":"¿Quién ganó el Balón de Oro en la Copa Mundial de 2022?","options":["Lionel Messi","Kylian Mbappé","Luka Modrić","Neymar"]},"fr":{"prompt":"Qui a remporté le Ballon d''or de la Coupe du monde 2022 ?","options":["Lionel Messi","Kylian Mbappé","Luka Modrić","Neymar"]}}'::jsonb),
  ('Who won the Golden Boot at the 2022 World Cup?', array['Kylian Mbappé','Lionel Messi','Olivier Giroud','Julián Álvarez'], 0, '2026-06-19', '{"es":{"prompt":"¿Quién ganó la Bota de Oro en la Copa Mundial de 2022?","options":["Kylian Mbappé","Lionel Messi","Olivier Giroud","Julián Álvarez"]},"fr":{"prompt":"Qui a remporté le Soulier d''or de la Coupe du monde 2022 ?","options":["Kylian Mbappé","Lionel Messi","Olivier Giroud","Julián Álvarez"]}}'::jsonb),
  ('Which country won the 1950 World Cup?', array['Uruguay','Brazil','Italy','Sweden'], 0, '2026-06-20', '{"es":{"prompt":"¿Qué país ganó la Copa Mundial de 1950?","options":["Uruguay","Brasil","Italia","Suecia"]},"fr":{"prompt":"Quel pays a remporté la Coupe du monde 1950 ?","options":["Uruguay","Brésil","Italie","Suède"]}}'::jsonb),
  ('How many times has Italy won the World Cup?', array['2','3','4','5'], 2, '2026-06-21', '{"es":{"prompt":"¿Cuántas veces ha ganado Italia la Copa Mundial?","options":["2","3","4","5"]},"fr":{"prompt":"Combien de fois l''Italie a-t-elle remporté la Coupe du monde ?","options":["2","3","4","5"]}}'::jsonb),
  ('Which African nation first reached a World Cup quarter-final?', array['Cameroon','Senegal','Ghana','Nigeria'], 0, '2026-06-22', '{"es":{"prompt":"¿Qué selección africana llegó por primera vez a unos cuartos de final de la Copa Mundial?","options":["Camerún","Senegal","Ghana","Nigeria"]},"fr":{"prompt":"Quelle nation africaine a été la première à atteindre un quart de finale de Coupe du monde ?","options":["Cameroun","Sénégal","Ghana","Nigeria"]}}'::jsonb),
  ('Who scored a hat-trick in the 1966 World Cup final?', array['Geoff Hurst','Bobby Charlton','Pelé','Eusébio'], 0, '2026-06-23', '{"es":{"prompt":"¿Quién marcó un triplete en la final de la Copa Mundial de 1966?","options":["Geoff Hurst","Bobby Charlton","Pelé","Eusébio"]},"fr":{"prompt":"Qui a inscrit un triplé en finale de la Coupe du monde 1966 ?","options":["Geoff Hurst","Bobby Charlton","Pelé","Eusébio"]}}'::jsonb),
  ('Which country lost the World Cup finals of 1974, 1978 and 2010?', array['Netherlands','Germany','Argentina','Hungary'], 0, '2026-06-24', '{"es":{"prompt":"¿Qué país perdió las finales de la Copa Mundial de 1974, 1978 y 2010?","options":["Países Bajos","Alemania","Argentina","Hungría"]},"fr":{"prompt":"Quel pays a perdu les finales de la Coupe du monde de 1974, 1978 et 2010 ?","options":["Pays-Bas","Allemagne","Argentine","Hongrie"]}}'::jsonb),
  ('In which year was the current World Cup trophy first awarded?', array['1974','1970','1982','1966'], 0, '2026-06-25', '{"es":{"prompt":"¿En qué año se entregó por primera vez el trofeo actual de la Copa Mundial?","options":["1974","1970","1982","1966"]},"fr":{"prompt":"En quelle année le trophée actuel de la Coupe du monde a-t-il été décerné pour la première fois ?","options":["1974","1970","1982","1966"]}}'::jsonb),
  ('Which city hosted the 2014 World Cup final?', array['Rio de Janeiro','São Paulo','Brasília','Belo Horizonte'], 0, '2026-06-26', '{"es":{"prompt":"¿Qué ciudad acogió la final de la Copa Mundial de 2014?","options":["Río de Janeiro","São Paulo","Brasilia","Belo Horizonte"]},"fr":{"prompt":"Quelle ville a accueilli la finale de la Coupe du monde 2014 ?","options":["Rio de Janeiro","São Paulo","Brasilia","Belo Horizonte"]}}'::jsonb),
  ('Who is often cited as the youngest player to score in a World Cup?', array['Pelé','Kylian Mbappé','Michael Owen','Diego Maradona'], 0, '2026-06-27', '{"es":{"prompt":"¿A quién se cita a menudo como el jugador más joven en marcar en una Copa Mundial?","options":["Pelé","Kylian Mbappé","Michael Owen","Diego Maradona"]},"fr":{"prompt":"Qui est souvent cité comme le plus jeune joueur à marquer en Coupe du monde ?","options":["Pelé","Kylian Mbappé","Michael Owen","Diego Maradona"]}}'::jsonb),
  ('How many World Cups has Germany (incl. West Germany) won?', array['2','3','4','5'], 2, '2026-06-28', '{"es":{"prompt":"¿Cuántas Copas Mundiales ha ganado Alemania (incl. Alemania Occidental)?","options":["2","3","4","5"]},"fr":{"prompt":"Combien de Coupes du monde l''Allemagne (RFA comprise) a-t-elle remportées ?","options":["2","3","4","5"]}}'::jsonb),
  ('Which goalkeeper captained Spain to the 2010 title?', array['Iker Casillas','Víctor Valdés','Pepe Reina','David de Gea'], 0, '2026-06-29', '{"es":{"prompt":"¿Qué portero fue capitán de España en el título de 2010?","options":["Iker Casillas","Víctor Valdés","Pepe Reina","David de Gea"]},"fr":{"prompt":"Quel gardien était le capitaine de l''Espagne lors du titre de 2010 ?","options":["Iker Casillas","Víctor Valdés","Pepe Reina","David de Gea"]}}'::jsonb),
  ('In which final was Zinedine Zidane sent off for a headbutt?', array['2006','1998','2002','2010'], 0, '2026-06-30', '{"es":{"prompt":"¿En qué final fue expulsado Zinedine Zidane por un cabezazo?","options":["2006","1998","2002","2010"]},"fr":{"prompt":"Lors de quelle finale Zinedine Zidane a-t-il été expulsé pour un coup de tête ?","options":["2006","1998","2002","2010"]}}'::jsonb),
  ('Who co-hosted the 2002 World Cup with Japan?', array['South Korea','China','Australia','Qatar'], 0, '2026-07-01', '{"es":{"prompt":"¿Quién fue coanfitrión de la Copa Mundial de 2002 junto a Japón?","options":["Corea del Sur","China","Australia","Catar"]},"fr":{"prompt":"Qui a coorganisé la Coupe du monde 2002 avec le Japon ?","options":["Corée du Sud","Chine","Australie","Qatar"]}}'::jsonb),
  ('How long is a standard World Cup match, excluding stoppage time?', array['90 minutes','80 minutes','100 minutes','120 minutes'], 0, '2026-07-02', '{"es":{"prompt":"¿Cuánto dura un partido estándar de la Copa Mundial, sin contar el tiempo añadido?","options":["90 minutos","80 minutos","100 minutos","120 minutos"]},"fr":{"prompt":"Combien de temps dure un match standard de Coupe du monde, hors temps additionnel ?","options":["90 minutes","80 minutes","100 minutes","120 minutes"]}}'::jsonb),
  ('Who won the Golden Boot at the 2018 World Cup?', array['Harry Kane','Kylian Mbappé','Romelu Lukaku','Antoine Griezmann'], 0, '2026-07-03', '{"es":{"prompt":"¿Quién ganó la Bota de Oro en la Copa Mundial de 2018?","options":["Harry Kane","Kylian Mbappé","Romelu Lukaku","Antoine Griezmann"]},"fr":{"prompt":"Qui a remporté le Soulier d''or de la Coupe du monde 2018 ?","options":["Harry Kane","Kylian Mbappé","Romelu Lukaku","Antoine Griezmann"]}}'::jsonb),
  ('Which country won the 2006 World Cup?', array['Italy','France','Germany','Brazil'], 0, '2026-07-04', '{"es":{"prompt":"¿Qué país ganó la Copa Mundial de 2006?","options":["Italia","Francia","Alemania","Brasil"]},"fr":{"prompt":"Quel pays a remporté la Coupe du monde 2006 ?","options":["Italie","France","Allemagne","Brésil"]}}'::jsonb),
  ('Which metro area hosts the 2026 World Cup final?', array['New York / New Jersey','Los Angeles','Dallas','Mexico City'], 0, '2026-07-05', '{"es":{"prompt":"¿Qué área metropolitana acoge la final de la Copa Mundial de 2026?","options":["Nueva York / Nueva Jersey","Los Ángeles","Dallas","Ciudad de México"]},"fr":{"prompt":"Quelle agglomération accueille la finale de la Coupe du monde 2026 ?","options":["New York / New Jersey","Los Angeles","Dallas","Mexico"]}}'::jsonb)
on conflict (active_on) do nothing;
