-- ===========================================================================
-- Daily Quiz — backfill es/fr translations onto already-seeded questions.
-- The seed (supabase/seed/quiz.sql) inserts these for fresh installs, but it is
-- "on conflict (active_on) do nothing", so databases seeded before translations
-- existed keep empty {} translations. This sets each question's translations by
-- its stable active_on key. Idempotent: re-running writes identical JSON, and
-- only the seeded active_on dates are touched (admin-authored rows untouched).
-- GENERATED from scripts/gen-quiz-translations.mjs — edit there, then re-run.
-- ===========================================================================

update public.quiz_questions set translations = '{"es":{"prompt":"¿Cada cuánto se celebra la Copa Mundial masculina de la FIFA?","options":["Cada 4 años","Cada 2 años","Cada 3 años","Cada año"]},"fr":{"prompt":"À quelle fréquence a lieu la Coupe du monde masculine de la FIFA ?","options":["Tous les 4 ans","Tous les 2 ans","Tous les 3 ans","Tous les ans"]}}'::jsonb where active_on = '2026-06-05';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué país ganó la primera Copa Mundial de la FIFA, en 1930?","options":["Uruguay","Brasil","Argentina","Italia"]},"fr":{"prompt":"Quel pays a remporté la première Coupe du monde de la FIFA, en 1930 ?","options":["Uruguay","Brésil","Argentine","Italie"]}}'::jsonb where active_on = '2026-06-06';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Cuántas Copas Mundiales ha ganado Brasil?","options":["3","4","5","6"]},"fr":{"prompt":"Combien de Coupes du monde le Brésil a-t-il remportées ?","options":["3","4","5","6"]}}'::jsonb where active_on = '2026-06-07';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué país organizó y ganó la Copa Mundial de 1998?","options":["Francia","Brasil","Italia","España"]},"fr":{"prompt":"Quel pays a organisé et remporté la Coupe du monde 1998 ?","options":["France","Brésil","Italie","Espagne"]}}'::jsonb where active_on = '2026-06-08';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Quién ganó la Copa Mundial de 2022 en Catar?","options":["Argentina","Francia","Croacia","Brasil"]},"fr":{"prompt":"Qui a remporté la Coupe du monde 2022 au Qatar ?","options":["Argentine","France","Croatie","Brésil"]}}'::jsonb where active_on = '2026-06-09';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Quién marcó el gol de «la Mano de Dios» en 1986?","options":["Diego Maradona","Pelé","Zico","Michel Platini"]},"fr":{"prompt":"Qui a marqué le but de « la Main de Dieu » en 1986 ?","options":["Diego Maradona","Pelé","Zico","Michel Platini"]}}'::jsonb where active_on = '2026-06-10';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué selección ha estado presente en todas las Copas Mundiales?","options":["Brasil","Alemania","Italia","Argentina"]},"fr":{"prompt":"Quelle nation a participé à toutes les Coupes du monde ?","options":["Brésil","Allemagne","Italie","Argentine"]}}'::jsonb where active_on = '2026-06-11';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Quién es el máximo goleador histórico en fases finales de la Copa Mundial?","options":["Miroslav Klose","Ronaldo","Gerd Müller","Pelé"]},"fr":{"prompt":"Qui est le meilleur buteur de l''histoire en phase finale de Coupe du monde ?","options":["Miroslav Klose","Ronaldo","Gerd Müller","Pelé"]}}'::jsonb where active_on = '2026-06-12';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Dónde se celebró la Copa Mundial de 1966?","options":["Inglaterra","Alemania Occidental","México","Chile"]},"fr":{"prompt":"Où s''est déroulée la Coupe du monde 1966 ?","options":["Angleterre","Allemagne de l''Ouest","Mexique","Chili"]}}'::jsonb where active_on = '2026-06-13';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué país ganó la Copa Mundial de 2010?","options":["España","Países Bajos","Alemania","Uruguay"]},"fr":{"prompt":"Quel pays a remporté la Coupe du monde 2010 ?","options":["Espagne","Pays-Bas","Allemagne","Uruguay"]}}'::jsonb where active_on = '2026-06-14';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Cuántos países organizan la Copa Mundial de 2026?","options":["1","2","3","4"]},"fr":{"prompt":"Combien de pays organisent la Coupe du monde 2026 ?","options":["1","2","3","4"]}}'::jsonb where active_on = '2026-06-15';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Cuántas selecciones juegan la Copa Mundial de 2026?","options":["32","40","48","64"]},"fr":{"prompt":"Combien d''équipes jouent la Coupe du monde 2026 ?","options":["32","40","48","64"]}}'::jsonb where active_on = '2026-06-16';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué país ganó la Copa Mundial de 2014?","options":["Alemania","Argentina","Brasil","Países Bajos"]},"fr":{"prompt":"Quel pays a remporté la Coupe du monde 2014 ?","options":["Allemagne","Argentine","Brésil","Pays-Bas"]}}'::jsonb where active_on = '2026-06-17';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Quién ganó el Balón de Oro en la Copa Mundial de 2022?","options":["Lionel Messi","Kylian Mbappé","Luka Modrić","Neymar"]},"fr":{"prompt":"Qui a remporté le Ballon d''or de la Coupe du monde 2022 ?","options":["Lionel Messi","Kylian Mbappé","Luka Modrić","Neymar"]}}'::jsonb where active_on = '2026-06-18';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Quién ganó la Bota de Oro en la Copa Mundial de 2022?","options":["Kylian Mbappé","Lionel Messi","Olivier Giroud","Julián Álvarez"]},"fr":{"prompt":"Qui a remporté le Soulier d''or de la Coupe du monde 2022 ?","options":["Kylian Mbappé","Lionel Messi","Olivier Giroud","Julián Álvarez"]}}'::jsonb where active_on = '2026-06-19';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué país ganó la Copa Mundial de 1950?","options":["Uruguay","Brasil","Italia","Suecia"]},"fr":{"prompt":"Quel pays a remporté la Coupe du monde 1950 ?","options":["Uruguay","Brésil","Italie","Suède"]}}'::jsonb where active_on = '2026-06-20';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Cuántas veces ha ganado Italia la Copa Mundial?","options":["2","3","4","5"]},"fr":{"prompt":"Combien de fois l''Italie a-t-elle remporté la Coupe du monde ?","options":["2","3","4","5"]}}'::jsonb where active_on = '2026-06-21';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué selección africana llegó por primera vez a unos cuartos de final de la Copa Mundial?","options":["Camerún","Senegal","Ghana","Nigeria"]},"fr":{"prompt":"Quelle nation africaine a été la première à atteindre un quart de finale de Coupe du monde ?","options":["Cameroun","Sénégal","Ghana","Nigeria"]}}'::jsonb where active_on = '2026-06-22';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Quién marcó un triplete en la final de la Copa Mundial de 1966?","options":["Geoff Hurst","Bobby Charlton","Pelé","Eusébio"]},"fr":{"prompt":"Qui a inscrit un triplé en finale de la Coupe du monde 1966 ?","options":["Geoff Hurst","Bobby Charlton","Pelé","Eusébio"]}}'::jsonb where active_on = '2026-06-23';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué país perdió las finales de la Copa Mundial de 1974, 1978 y 2010?","options":["Países Bajos","Alemania","Argentina","Hungría"]},"fr":{"prompt":"Quel pays a perdu les finales de la Coupe du monde de 1974, 1978 et 2010 ?","options":["Pays-Bas","Allemagne","Argentine","Hongrie"]}}'::jsonb where active_on = '2026-06-24';
update public.quiz_questions set translations = '{"es":{"prompt":"¿En qué año se entregó por primera vez el trofeo actual de la Copa Mundial?","options":["1974","1970","1982","1966"]},"fr":{"prompt":"En quelle année le trophée actuel de la Coupe du monde a-t-il été décerné pour la première fois ?","options":["1974","1970","1982","1966"]}}'::jsonb where active_on = '2026-06-25';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué ciudad acogió la final de la Copa Mundial de 2014?","options":["Río de Janeiro","São Paulo","Brasilia","Belo Horizonte"]},"fr":{"prompt":"Quelle ville a accueilli la finale de la Coupe du monde 2014 ?","options":["Rio de Janeiro","São Paulo","Brasilia","Belo Horizonte"]}}'::jsonb where active_on = '2026-06-26';
update public.quiz_questions set translations = '{"es":{"prompt":"¿A quién se cita a menudo como el jugador más joven en marcar en una Copa Mundial?","options":["Pelé","Kylian Mbappé","Michael Owen","Diego Maradona"]},"fr":{"prompt":"Qui est souvent cité comme le plus jeune joueur à marquer en Coupe du monde ?","options":["Pelé","Kylian Mbappé","Michael Owen","Diego Maradona"]}}'::jsonb where active_on = '2026-06-27';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Cuántas Copas Mundiales ha ganado Alemania (incl. Alemania Occidental)?","options":["2","3","4","5"]},"fr":{"prompt":"Combien de Coupes du monde l''Allemagne (RFA comprise) a-t-elle remportées ?","options":["2","3","4","5"]}}'::jsonb where active_on = '2026-06-28';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué portero fue capitán de España en el título de 2010?","options":["Iker Casillas","Víctor Valdés","Pepe Reina","David de Gea"]},"fr":{"prompt":"Quel gardien était le capitaine de l''Espagne lors du titre de 2010 ?","options":["Iker Casillas","Víctor Valdés","Pepe Reina","David de Gea"]}}'::jsonb where active_on = '2026-06-29';
update public.quiz_questions set translations = '{"es":{"prompt":"¿En qué final fue expulsado Zinedine Zidane por un cabezazo?","options":["2006","1998","2002","2010"]},"fr":{"prompt":"Lors de quelle finale Zinedine Zidane a-t-il été expulsé pour un coup de tête ?","options":["2006","1998","2002","2010"]}}'::jsonb where active_on = '2026-06-30';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Quién fue coanfitrión de la Copa Mundial de 2002 junto a Japón?","options":["Corea del Sur","China","Australia","Catar"]},"fr":{"prompt":"Qui a coorganisé la Coupe du monde 2002 avec le Japon ?","options":["Corée du Sud","Chine","Australie","Qatar"]}}'::jsonb where active_on = '2026-07-01';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Cuánto dura un partido estándar de la Copa Mundial, sin contar el tiempo añadido?","options":["90 minutos","80 minutos","100 minutos","120 minutos"]},"fr":{"prompt":"Combien de temps dure un match standard de Coupe du monde, hors temps additionnel ?","options":["90 minutes","80 minutes","100 minutes","120 minutes"]}}'::jsonb where active_on = '2026-07-02';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Quién ganó la Bota de Oro en la Copa Mundial de 2018?","options":["Harry Kane","Kylian Mbappé","Romelu Lukaku","Antoine Griezmann"]},"fr":{"prompt":"Qui a remporté le Soulier d''or de la Coupe du monde 2018 ?","options":["Harry Kane","Kylian Mbappé","Romelu Lukaku","Antoine Griezmann"]}}'::jsonb where active_on = '2026-07-03';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué país ganó la Copa Mundial de 2006?","options":["Italia","Francia","Alemania","Brasil"]},"fr":{"prompt":"Quel pays a remporté la Coupe du monde 2006 ?","options":["Italie","France","Allemagne","Brésil"]}}'::jsonb where active_on = '2026-07-04';
update public.quiz_questions set translations = '{"es":{"prompt":"¿Qué área metropolitana acoge la final de la Copa Mundial de 2026?","options":["Nueva York / Nueva Jersey","Los Ángeles","Dallas","Ciudad de México"]},"fr":{"prompt":"Quelle agglomération accueille la finale de la Coupe du monde 2026 ?","options":["New York / New Jersey","Los Angeles","Dallas","Mexico"]}}'::jsonb where active_on = '2026-07-05';
